def includeme(config):
    config.add_static_view('static', 'static', cache_max_age=3600)
    config.add_route('about', '/')
    config.add_route('signup', '/signup')
    config.add_route('login', '/login')
    config.add_route('logout', '/logout')
    config.add_route('search', '/search')
    config.add_route('results', '/search/results')
    config.add_route('register', '/search/results/{id}/register')
    config.add_route('profile', '/profile/{id:\d+}/')
    config.add_route('edit_profile', '/profile/{id:\d+}/{action}')
